### ISSUE TITLE
Missing Entry in Config

### ISSUE THREAD

**Issue by dpill83** [SimplexDevelopment/ToolAssist#1]
I've deleted the config and rebooted the server but the same error keeps reoccuring.

[03:39:23] [Server thread/INFO]: [ToolAssist] Enabling ToolAssist vv1.0-Alpha
[03:39:23] [Server thread/INFO]: [ToolAssist] Initializing configuration...
[03:39:23] [Server thread/ERROR]: [ToolAssist] Configuration is missing an entry, attempting to replace...
[03:39:23] [Server thread/ERROR]: Error occurred while enabling ToolAssist vv1.0-Alpha (Is it up to date?)
java.lang.RuntimeException: Unable to fix your configuration file. Please delete the config.yml in the data folder and restart your server.
	at io.github.simplex.toolassist.data.Config.lambda$new$4(Config.java:52) ~[ToolAssist-v1.0-Alpha.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at io.github.simplex.toolassist.data.Config.<init>(Config.java:48) ~[ToolAssist-v1.0-Alpha.jar:?]
	at io.github.simplex.toolassist.ToolAssist.onEnable(ToolAssist.java:18) ~[ToolAssist-v1.0-Alpha.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enabl
[latest.log](https://github.com/SimplexDevelopment/ToolAssist/files/8713154/latest.log)
ePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-317]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-317]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-317]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-317]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-317]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-317]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-317]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[03:39:23] [Server thread/INFO]: [ToolAssist] Disabling ToolAssist vv1.0-Alpha
[03:39:23] [Server thread/INFO]: [ToolAssist] Saving configuration...
[03:39:23] [Server thread/ERROR]: Error occurred while disabling ToolAssist vv1.0-Alpha (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "io.github.simplex.toolassist.data.Config.osave()" because "this.config" is null
	at io.github.simplex.toolassist.ToolAssist.onDisable(ToolAssist.java:29) ~[ToolAssist-v1.0-Alpha.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:578) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-317]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-317]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-317]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-317]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-317]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-317]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-317]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Paldiu** [comment]
Thanks for raising this; can you post the contents of the configuration file that the plugin generates?

**Comment by dpill83** [comment]
[config.yml.txt](https://github.com/SimplexDevelopment/ToolAssist/files/8718445/config.yml.txt)

**Comment by Paldiu** [comment]
Looks like an issue with the scanner. Thanks! I'll have a patch posted soon
