### ISSUE TITLE
Could not pass event BlockBreakEvent to ToolAssist 

### ISSUE THREAD

**Issue by dpill83** [SimplexDevelopment/ToolAssist#2]
[01:23:09] [Server thread/ERROR]: [latest.log](https://github.com/SimplexDevelopment/ToolAssist/files/8746136/latest.log)vv1.0-Alpha
java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.getString(String, String)" because "this.plugin_settings" is null
	at io.github.simplex.toolassist.data.Config$Settings.permission(Config.java:69) ~[ToolAssist-v1.0-Alpha.jar:?]
	at io.github.simplex.toolassist.play.MineListener.activate(MineListener.java:28) ~[ToolAssist-v1.0-Alpha.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor46.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-317]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:412) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.tick(ServerPlayerGameMode.java:151) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.tick(ServerPlayer.java:624) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1134) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:936) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:673) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[paper-1.18.2.jar:git-Paper-317]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:653) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1591) ~[paper-1.18.2.jar:git-Paper-317]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-317]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-317]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-317]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-317]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Paldiu** [comment]
Can you try and delete your config file and regenerate everything?
